WIP ssh

diff --git a/motley-confedit b/motley-confedit
--- a/motley-confedit
+++ b/motley-confedit
@@ -61,31 +61,26 @@ motley_confedit() {
   # the user hasn't indicated that a dotfile should be modified by motley.
   # Motley is very conservative about this since it's bad practice to blow away
   # people's dotfiles. So we die immediately and explain to the user how to fix
-  # the problem.
+  # the problem. The second check is done in motley_confedit_commit. It's
+  # important to do it there because it minimizes the time between checking the
+  # file's editability and modifying it.
 
   local var=$1
   local file=$2
-  local link=$(mktemp -u "$file.XXXXXXXX")
+  local link=$(mktemp -u "$file.motley_staging.XXXXXXXX")
 
-  # Look for a template file and make sure the original contains the "generated
-  # by motley" marker (the string MOTLEYGEN).
+  # Look for a template file. If we don't have one, copy the original to the
+  # staging location -- but most likely the original file has no MOTLEYGEN tag
+  # anyway, so the edit will ultimately fail.
   if ! [[ -r "$file.motley" ]]; then
-    echo "motley: attempted a configuration file edit on $file," >&2
-    echo "        but $file.motley (the template) doesn't exist" >&2
-    echo "        (run motley -h templates for info about this)" >&2
-    exit 1
+    echo "motley: using creating $file.motley as a template for $file"     >&2
+    echo "        (though unless $file contains the MOTLEYGEN tag nothing" >&2
+    echo "         will happen)"                                           >&2
+    cp "$file" "$file.motley"
   fi
 
-  if [[ -r "$file" ]] && ! grep -q "MOTLEYGEN" "$file"; then
-    echo "motley: attempted a configuration file edit on $file,"   >&2
-    echo "        but it doesn't appear to have been generated by" >&2
-    echo "        motley -- cowardly refusing to change anything"  >&2
-    echo "        (run motley -h templates for info about this)"   >&2
-    exit 1
-  fi
-
-  # At this point it's ok to edit the file, so set up the staging file (if it
-  # doesn't exist already) and hand out a hardlink to it.
+  # Set up a staging file if it doesn't exist yet and hand out a hardlink to
+  # it.
   local stage=$file.motley_staging
   [[ -e $stage ]] || cp "$file.motley" "$stage"
   ln "$stage" "$link"
@@ -104,14 +99,31 @@ motley_confedit_commit() {
     exit 1
   fi
 
-  local stage=${link%.*}.motley_staging
+  local stage=${link%.*}
   rm "$link"
 
   # If we've just removed the last link to the staging file, then move it over
   # the file it represents. Otherwise do nothing since other modules are still
   # editing it.
   if [[ $(stat -c %h "$stage") = 1 ]]; then
-    chmod -w "$stage"
-    mv -f "$stage" "${stage%.motley_staging}"
+    local file="${stage%.motley_staging}"
+    if [[ -r "$file" ]] && ! grep -q "MOTLEYGEN" "$file"; then
+      # Move the staging file into a tempfile and then complain. We can't leave
+      # the staging file where it is, because future invocations of motley will
+      # then assume it's in the middle of a concurrent edit and use it. The
+      # right answer for that situation is to reinit the staging file from the
+      # motley template.
+      local tempfile=$(mktemp "$stage.XXXX")
+      mv -f "$stage" "$tempfile"
+      echo "motley: attempted a configuration file edit on $file,"   >&2
+      echo "        but it doesn't appear to have been generated by" >&2
+      echo "        motley -- cowardly refusing to change anything"  >&2
+      echo "        (run motley -h templates for info about this)"   >&2
+      echo "        the staging file is available at $tempfile"      >&2
+      return 1
+    else
+      chmod -w "$stage"
+      mv -f "$stage" "$file"
+    fi
   fi
 }
